//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/protocolelement/selectivity/DestinationMacAddressHeader.msg.
//

#ifndef __INET_DESTINATIONMACADDRESSHEADER_M_H
#define __INET_DESTINATIONMACADDRESSHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class DestinationMacAddressHeader;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/linklayer/common/MacAddress_m.h" // import inet.linklayer.common.MacAddress


namespace inet {

/**
 * Class generated from <tt>inet/protocolelement/selectivity/DestinationMacAddressHeader.msg:14</tt> by opp_msgtool.
 * <pre>
 * class DestinationMacAddressHeader extends FieldsChunk
 * {
 *     chunkLength = B(6);
 *     MacAddress destinationAddress;
 * }
 * </pre>
 */
class INET_API DestinationMacAddressHeader : public ::inet::FieldsChunk
{
  protected:
    MacAddress destinationAddress;

  private:
    void copy(const DestinationMacAddressHeader& other);

  protected:
    bool operator==(const DestinationMacAddressHeader&) = delete;

  public:
    DestinationMacAddressHeader();
    DestinationMacAddressHeader(const DestinationMacAddressHeader& other);
    virtual ~DestinationMacAddressHeader();
    DestinationMacAddressHeader& operator=(const DestinationMacAddressHeader& other);
    virtual DestinationMacAddressHeader *dup() const override {return new DestinationMacAddressHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const MacAddress& getDestinationAddress() const;
    virtual MacAddress& getDestinationAddressForUpdate() { handleChange();return const_cast<MacAddress&>(const_cast<DestinationMacAddressHeader*>(this)->getDestinationAddress());}
    virtual void setDestinationAddress(const MacAddress& destinationAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DestinationMacAddressHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DestinationMacAddressHeader& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::DestinationMacAddressHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::DestinationMacAddressHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_DESTINATIONMACADDRESSHEADER_M_H

