//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/protocolelement/checksum/header/CrcHeader.msg.
//

#ifndef __INET_CRCHEADER_M_H
#define __INET_CRCHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class CrcHeader;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/transportlayer/common/CrcMode_m.h" // import inet.transportlayer.common.CrcMode


namespace inet {

/**
 * Class generated from <tt>inet/protocolelement/checksum/header/CrcHeader.msg:14</tt> by opp_msgtool.
 * <pre>
 * class CrcHeader extends FieldsChunk
 * {
 *     chunkLength = B(2);
 *     uint16_t crc = 0;
 *     CrcMode crcMode = CRC_MODE_UNDEFINED;
 * }
 * </pre>
 */
class INET_API CrcHeader : public ::inet::FieldsChunk
{
  protected:
    uint16_t crc = 0;
    CrcMode crcMode = CRC_MODE_UNDEFINED;

  private:
    void copy(const CrcHeader& other);

  protected:
    bool operator==(const CrcHeader&) = delete;

  public:
    CrcHeader();
    CrcHeader(const CrcHeader& other);
    virtual ~CrcHeader();
    CrcHeader& operator=(const CrcHeader& other);
    virtual CrcHeader *dup() const override {return new CrcHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint16_t getCrc() const;
    virtual void setCrc(uint16_t crc);

    virtual CrcMode getCrcMode() const;
    virtual void setCrcMode(CrcMode crcMode);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CrcHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CrcHeader& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::CrcHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CrcHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_CRCHEADER_M_H

