//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/protocolelement/shaper/EligibilityTimeTag.msg.
//

#ifndef __INET_ELIGIBILITYTIMETAG_M_H
#define __INET_ELIGIBILITYTIMETAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class EligibilityTimeTag;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/clock/contract/ClockTime_m.h" // import inet.clock.contract.ClockTime


namespace inet {

/**
 * Class generated from <tt>inet/protocolelement/shaper/EligibilityTimeTag.msg:22</tt> by opp_msgtool.
 * <pre>
 * //
 * // This tag specifies the simulation time after which the packet becomes eligible
 * // for transmission according to the asynchronous shaper.
 * //
 * // This tag is used by the asynchronous shaper infrastructure.
 * //
 * // \@see ~EligibilityTimeGate, ~EligibilityTimeFilter, ~EligibilityTimeMeter, ~EligibilityTimeQueue
 * //
 * class EligibilityTimeTag extends TagBase
 * {
 *     clocktime_t eligibilityTime; // the simulation time after which the packet is eligible for transmission
 * }
 * </pre>
 */
class INET_API EligibilityTimeTag : public ::inet::TagBase
{
  protected:
    clocktime_t eligibilityTime = CLOCKTIME_ZERO;

  private:
    void copy(const EligibilityTimeTag& other);

  protected:
    bool operator==(const EligibilityTimeTag&) = delete;

  public:
    EligibilityTimeTag();
    EligibilityTimeTag(const EligibilityTimeTag& other);
    virtual ~EligibilityTimeTag();
    EligibilityTimeTag& operator=(const EligibilityTimeTag& other);
    virtual EligibilityTimeTag *dup() const override {return new EligibilityTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual clocktime_t getEligibilityTime() const;
    virtual void setEligibilityTime(clocktime_t eligibilityTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EligibilityTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EligibilityTimeTag& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::EligibilityTimeTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::EligibilityTimeTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_ELIGIBILITYTIMETAG_M_H

