//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/transportlayer/common/CrcMode.msg.
//

#ifndef __INET_CRCMODE_M_H
#define __INET_CRCMODE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {


}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs


namespace inet {

/**
 * Enum generated from <tt>inet/transportlayer/common/CrcMode.msg:12</tt> by opp_msgtool.
 * <pre>
 * enum CrcMode
 * {
 *     CRC_MODE_UNDEFINED = -1; // mode is undefined, CRC is not yet set, not serializable
 *     CRC_DISABLED = 0; // CRC is disabled (not set), serializable
 *     CRC_DECLARED_CORRECT = 1; // CRC is correctly set without the actual value, not serializable
 *     CRC_DECLARED_INCORRECT = 2; // the CRC is incorrectly set without the actual value, not serializable
 *     CRC_COMPUTED = 3; // CRC is set to a value that is potentially incorrect, serializable
 * }
 * </pre>
 */
enum CrcMode {
    CRC_MODE_UNDEFINED = -1,
    CRC_DISABLED = 0,
    CRC_DECLARED_CORRECT = 1,
    CRC_DECLARED_INCORRECT = 2,
    CRC_COMPUTED = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CrcMode& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CrcMode& e) { int n; b->unpack(n); e = static_cast<CrcMode>(n); }

// cplusplus {{
INET_API CrcMode parseCrcMode(const char *crcModeString, bool allowDisable);
// }}


}  // namespace inet


namespace omnetpp {


}  // namespace omnetpp

#endif // ifndef __INET_CRCMODE_M_H

