name: check quisp
on: [push, pull_request]
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    container:
      image: omnetpp/omnetpp:u18.04-5.6.2
      # volumes:
      #   - ./:/root/quisp
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: make ci
        working-directory: ${GITHUB_WORKSPACE}
      - run: docker run --rm -i -v "${GITHUB_WORKSPACE}/root/quisp" quisp /bin/sh -c "cd /root/quisp/; make ci"
        working-directory: ${GITHUB_WORKSPACE}
      - run: /bin/bash test.sh
        working-directory: ${GITHUB_WORKSPACE}/test
      - run: sudo python -m unittest discover && sudo rm testresults.txt && echo "test done"
        working-directory: ${GITHUB_WORKSPACE}/test

