name: check quisp
on: [push, pull_request]
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    container:
      image: omnetpp/omnetpp:u18.04-5.6.2
      # volumes:
      #   - ./:/root/quisp
    steps:
      - run: |
          apt-get update -y
          apt-get install -y --no-install-recommends software-properties-common cmake g++ clang-format clang-tidy
          apt-get update -y
          apt-get install git
      - name: Check out repository
        uses: actions/checkout@v2
      - run: pwd; ls -la; ls -la ..; ls -la quisp;
      - run: make ci
      - run: /bin/bash test.sh
        working-directory: ${GITHUB_WORKSPACE}/test
      - run: sudo python -m unittest discover && sudo rm testresults.txt && echo "test done"
        working-directory: ${GITHUB_WORKSPACE}/test

